export { default as Welcome } from './Welcome.vue'
export { default as MyNavbar } from './MyNavbar.vue'
export { default as AboutUs } from './AboutUs.vue'
export { default as Gallery } from './Gallery.vue'
export { default as MyFooter } from './MyFooter.vue'
