export { default as Welcome } from './Welcome.vue'
export { default as Navbar } from './Navbar.vue'
export { default as AboutUs } from './AboutUs.vue'
export { default as Gallery } from './Gallery.vue'
export { default as Footer } from './Footer.vue'
